application:
  subdomain: we-rss
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://we-rss:8001/
services:
  we-rss:
    # upstream: ghcr.io/rachelos/we-mp-rss:latest@sha256:1b7f126836bab9e726207756f6483d4771a7405fa35b5d044c64901eeb79e2d7
    image: registry.lazycat.cloud/czyt/rachelos/we-mp-rss:413eadcea1f58f01
    environment:
      - DB=sqlite:///data/db.db
      - USERNAME={{.U.auth_user}}
      - PASSWORD={{.U.auth_pass}}
    binds:
      - /lzcapp/var/data:/app/data
